# Generated by Django 3.2 on 2023-03-11 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('accounts', '0002_profile_my_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='my_city',
            field=models.ForeignKey(default='andimeshk', on_delete=django.db.models.deletion.PROTECT, related_name='my_city', to='locations.city'),
        ),
    ]
