# Generated by Django 3.2 on 2023-03-11 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_my_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='my_city',
        ),
    ]
