# Generated by Django 3.2 on 2023-03-16 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Mobile Number')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Fresh')], default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_category', to='category.category', verbose_name='Category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_location', to='locations.location', verbose_name='Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
