# Generated by Django 3.2 on 2023-03-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('NEW', 'New'), ('FRESH', 'Fresh')], default='NEW'),
        ),
    ]
