# Generated by Django 3.2 on 2023-03-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_alter_advertisement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Fresh')], default=1),
        ),
    ]
